# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-22 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0003_auto_20160622_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
